### ISSUE TITLE
Get ID When creating server.

### ISSUE THREAD

**Issue by DomiHrajeCZ-Developer** [mattmalec/Pterodactyl4J#1]
Hello, can i after server installation get ID of Server? How? 

Thanks

Domi

**Comment by mattmalec** [comment]
Are you asking how to get a server ID after using the `createServer` function?

**Comment by DomiHrajeCZ-Developer** [comment]
yes

**Comment by mattmalec** [comment]
The `createServer` method returns a `PteroAction<ApplicationServer>`. Just execute the request and you’ll get an `ApplicationServer`. From there, it’s just `Server#getId`

**Comment by DomiHrajeCZ-Developer** [comment]
Please, how?

**Comment by mattmalec** [comment]
I just told you how?

**Comment by DomiHrajeCZ-Developer** [comment]
how to execute request, please?

**Comment by mattmalec** [comment]
It’s `PteroAction#execute`

**Comment by DomiHrajeCZ-Developer** [comment]
oh, thanks

**Comment by mattmalec** [comment]
I'm going to close this now as this issue has been resolved.

**Comment by Clayun** [comment]
and how to get the client id?
