### ISSUE TITLE
Error on oom_disabled

### ISSUE THREAD

**Issue by belinazzi** [mattmalec/Pterodactyl4J#10]
Hello, **congratulations for your work**, very **good** and **organizated**!

When we try to update any machine resource of one server we have an internal server error.

I checked the pterodactyl logs and founded the error on the request (Not sending oom_disabled value).

Fast solution: change pterodactyl BuildModificationService.php, line 88  to **'oom_disabled' => false,**

For implementation: add oom_disabled support on the request functions.

Its only a report!

Thanks

**Comment by belinazzi** [comment]
For reference, this is code that generate the problem (Kotlin code):

    _fun updateServer(id:Long, cpu:Long, memory: Long, disk: Long){
        val api = startApi()

        api.retrieveServerById(id).execute().manager.setCPU(cpu).execute()
        api.retrieveServerById(id).execute().manager.setMemory(memory, DataType.GB).execute()
        api.retrieveServerById(id).execute().manager.setDisk(disk, DataType.GB).execute()

    }_

**Comment by mattmalec** [comment]
This error has nothing to do with Pterodactyl4J. Please report it to the Pterodactyl Discord server.
