### ISSUE TITLE
Verifying user account passwords.

### ISSUE THREAD

**Issue by bradcarnage** [mattmalec/Pterodactyl4J#12]
I've searched and i'm not sure this is possible in the current implementation. I understand that you can set a user account password via the api, but what about *verifying* it?

**Comment by mattmalec** [comment]
Define "verifying". What do you mean?

**Comment by bradcarnage** [comment]
you submit a password for a given user, and somehow (through some function) a boolean is returned stating whether that password was or wasn't "correct"; essentially verifying that user's credentials.

**Comment by mattmalec** [comment]
No, this isn’t possible and for good reason. If that feature existed, it would be a detrimental breach of security.

**Comment by bradcarnage** [comment]
Not if the verification process is done via the panel itself, and ratelimited (just like the web UI). I mean, i have the option to set passwords, so why not verify? ¯\\\_(ツ)\_/¯

**Comment by bradcarnage** [comment]
of course there's always the option of a malicious scripter to do malicious things and getting cleartext passwords straight from users, but at that point you've got bigger issues i suppose. (like having users putting their passwords into a form on a webpage or program whilst not checking if it's "safe") or having said malicious scripter nuke the ptero instance, etc.

**Comment by mattmalec** [comment]
I don’t really understand why you’re complaining to me. I wrote a wrapper that wraps the API. If you can’t find something you’re looking for, then it doesn’t exist. That being said, my original point still stands.
