### ISSUE TITLE
Creating application: Having URL with "/" at the end causing an exception

### ISSUE THREAD

**Issue by lilmayu** [mattmalec/Pterodactyl4J#19]
**Version**: 2.BETA_33
 
 - **Exception**: NotFoundException: The requested entity was not found.
 - **Steps to reproduce**:
     - Change URL argument in PteroBuilder.createApplication() to have "/" at the end
     - Example: `PteroBuilder.createApplication("https://panel.lilmayu.tech/", "*token*");`
 - **Simple fix**
     - Remove "/" in url, like so: `PteroBuilder.createApplication("https://panel.lilmayu.tech", "*token*");`
 
It is not something ground-breaking, but it took me solid 30 minutes to found out.

**Comment by mattmalec** [comment]
This is now fixed in the `2.BETA_34`. Let me know if this issue still persists for you. Thanks!
