### ISSUE TITLE
Create Server:  Assign multiple ports

### ISSUE THREAD

**Issue by fo0** [mattmalec/Pterodactyl4J#20]
Is there any way to assign more then one port when you create a server?
I saw that we can set a port range, but it looks like that this is just a range for the gameport.
It would be nice if we get the possibility to assign additional ports like in the UI that a gameserver has i.e. 2 ports "4000 + 4001"

anyway, thanks for the nice api client - its great :)

**Comment by mattmalec** [comment]
This is possible with `ServerAction#setAllocations`. You can get an Allocation to pass into this method with `Node#getAllocations` and `Node#getAllocationsByPort`. Hope this helps!

**Comment by fo0** [comment]
great! thanks for your fast answer. I will gonna try and give you feedback if it works :)

**Comment by fo0** [comment]
works! thank you :)
