### ISSUE TITLE
PteroClient login help

### ISSUE THREAD

**Issue by fo0** [mattmalec/Pterodactyl4J#21]
Hi again :)

PteroApplication is great and I had no problems with it at all. 
Now im testing the PteroClient and running into login problems when calling

```java
# ---- with same credentials -- token ALL read/write
# init application
PteroBuilder.createApplication(ptero.getHost(), ptero.getApiKey())
# init client ---- ERROR AT CLIENT
PteroBuilder.createClient(ptero.getHost(), ptero.getApiKey())
```
```log4j
com.mattmalec.pterodactyl4j.exceptions.LoginException: 
The provided token is either incorrect or does not have access to process this request
```

Any idea what I am doing wrong?

> PteroBuilder.createApplication(ptero.getHost(), ptero.getApiKey())

works pretty good and everything is fine.

I was trying to find something in your README but I wasn't successful

**Comment by mattmalec** [comment]
Client API and Application API are completely different. So you'll need to use an Application API key for the Application API and a Client API key for the Client API.

**Comment by fo0** [comment]
alright, thanks for explaination. Where to get this key? Is this the key for each wing (per wing, 1 key)?

**Comment by mattmalec** [comment]
It's per user account. You can get one by going to My Account > API Credentials

**Comment by fo0** [comment]
great, thank you. Do you know, that admin user acc token can control all servers? Or do I really need the related user token to each server?

**Comment by mattmalec** [comment]
If the user is an admin, they should have access to every server on the panel.

**Comment by fo0** [comment]
alright, thank you :) great support!
