### ISSUE TITLE
Websocket console - Ability to close connection

### ISSUE THREAD

**Issue by theFra985** [mattmalec/Pterodactyl4J#22]
Hi,
I started to look into this library to use for interacting with the Pterodactyl API and while checking its capabilities I noticed there is no function allowing you to close the websocket build using the WebSocketBuilder.
I suppose you can unregister the handlers but it seems more like a workaround and I would prefer being able to stop the connection to the server to save resources.
Am I missing something?
Thanks in advance for your help.
Have a great day,
Francesco

**Comment by mattmalec** [comment]
You can't close the WebSocket with the builder since it's just a builder, but you can use the WebSocketManager to close it. `WebSocketManager#shutdown` should do the trick.

**Comment by theFra985** [comment]
Oh, okay
I thought the shutdown would shutdown the server itself
Thanks
