### ISSUE TITLE
Exception when using PteroClient to read console output

### ISSUE THREAD

**Issue by Exceptionflug** [mattmalec/Pterodactyl4J#24]
Hello,

I'm experiencing some difficulties when using the WebSocketBuilder. I followed the example shown in the README.MD file, but it won't work. I'm only getting the following exception:
```
20:27:06 [SEVERE]: There was an error in the websocket for server 8b837667
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:186)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:157)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

This is my source code: http://paste.cytooxien.de/lobasomiqe.java

I also tried authenticating using the method, but this won't change anything.

The api key used for the client is created by the administrative user which owns the server that I'm trying to access. Every other client api actions are working fine.

**Comment by mattmalec** [comment]
This error is common and I should probably have a FAQ for it. 

Wings by default blocks all incoming websocket connections that don't come directly from the panel. To allow connections from additional origins, you need to modify the `allowed_origins` array in your `config.yml` file in `/etc/pterodactyl`. You can either specify specific IP addresses or use `*` as a wildcard allowing all IPs to access the Wings websocket.

**Example:**
```yaml
allowed_origins:
- '*'
```
After modifying the config file, make sure you restart Wings to apply the changes.

Let me know if this helps, thanks!

**Comment by Exceptionflug** [comment]
Yes thank you. This solved the problem for me :)
