### ISSUE TITLE
Updating environment variables of existing server

### ISSUE THREAD

**Issue by Exceptionflug** [mattmalec/Pterodactyl4J#25]
Hey,

how can I update an existing servers environment variables? I found the following method:
```java
applicationServer.getManager().setEnvironment();
```
But this method accepts a `Set<String>` which makes no sense. According to the [api docs](https://dashflo.net/docs/api/pterodactyl/v1/#req_17bb4d3166db42d889e07bce02acfbad) this must be a map.

**Comment by mattmalec** [comment]
This must've been one of those methods I missed when migrating the wrapper. On Pterodactyl 0.7, it actually accepted a String array instead of a Map. This will be fixed with the next update.
