### ISSUE TITLE
Updating Server

### ISSUE THREAD

**Issue by belinazzi** [mattmalec/Pterodactyl4J#32]
Please, can you provide a example to update egg and Enviroment Values at the same time?

                    server.manager.setEgg(egg).execute()
                    server.manager.setEnvironment(map).execute()

**Comment by mattmalec** [comment]
You can use the new [PteroAction#flatMap](https://ci.mattmalec.com/job/Pterodactyl4J/javadoc/com/mattmalec/pterodactyl4j/PteroAction.html#flatMap(java.util.function.Function)) to do this:
```java
ServerManager manager = server.getManager();
manager.setEgg(egg)
    .flatMap(manager.setEnvironment(map))
    .executeAsync();
```

**Comment by belinazzi** [comment]
Hi, i dont now if the problem is kotlin (Im not using java), but the only way to update a server is:
Thanks for your work, its a very good wrapper, and its a info feedback only, all is ok.

////////////////////NOT WORKING

                val server = api.retrieveServerById(serverid).execute()

                val nest: Nest = api.retrieveNestById("1").execute()
                val egg: ApplicationEgg = api.retrieveEggById(nest, "5").execute()


                val map: MutableMap<String, EnvironmentValue<*>> = HashMap()
                map["SERVER_JARFILE"] = EnvironmentValue.ofString("server.jar")
                map["VANILLA_VERSION"] = EnvironmentValue.ofString("latest")


                server.manager.setEgg(egg).execute()
                server.manager.setEnvironment(map).execute()
                server.manager.setSkipScripts(false).execute()
                server.controller.reinstall().execute(true)

/////////////////////////// WORKING 

                val nest: Nest = api.retrieveNestById(6).execute()
                val egg: ApplicationEgg = api.retrieveEggById(nest, 19).execute()


                val map: MutableMap<String, EnvironmentValue<*>> = HashMap()
                map["FTB_MODPACK_ID"] = EnvironmentValue.ofString(ftbId)
                map["FTB_MODPACK_VERSION_ID"] = EnvironmentValue.ofString(ftbVersion)

                api.retrieveServerById(serverid).execute().manager.setEgg(egg).execute()
                    .manager.setEnvironment(map).execute()
                    .manager.setSkipScripts(false).execute()
                    .controller.reinstall().execute()
