### ISSUE TITLE
Deleting Server don't work

### ISSUE THREAD

**Issue by ghost** [mattmalec/Pterodactyl4J#33]
Hey i think i find a issue in p4j because when i wan't to delete a server , the server aren't delete 
![image](https://user-images.githubusercontent.com/81041750/128520781-8ecc963a-2e19-48e9-bef8-748aceb529c7.png)
And i have no error in my console , i sent you the log for confirm , nothing is null , the system.out.println doesn't print null
[logpterobug.txt](https://github.com/mattmalec/Pterodactyl4J/files/6945957/logpterobug.txt)

**Comment by mattmalec** [comment]
`delete` is a PteroAction and needs to be executed the same way you executed the `retrieveServerById` method.

**Comment by ghost** [comment]
Yes sorry now that work ^^
