### ISSUE TITLE
No enum constant com.mattmalec.pterodactyl4j.ServerStatus.installing

### ISSUE THREAD

**Issue by ghost** [mattmalec/Pterodactyl4J#34]
I have this issue print in my console but it's happen when i wan't to get the status
![image](https://user-images.githubusercontent.com/81041750/128522983-fc3c40f5-adec-4882-b0ac-e2a7bf0fd9eb.png)
![image](https://user-images.githubusercontent.com/81041750/128523025-911be7dc-b683-46a1-bf7e-05da075313a1.png)

**Comment by mattmalec** [comment]
Good catch! Feel free to PR this fix. Should just be swapping `toLowerCase` to `toUpperCase` 

https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/application/entities/impl/ApplicationServerImpl.java#L188
