### ISSUE TITLE
NullPointerException when trying to set / add ports on an allocation.

### ISSUE THREAD

**Issue by Zentae** [mattmalec/Pterodactyl4J#38]
Version: latest (2.BETA_72)

Hello ! I've been trying to automatically create allocation via P4J however i get this stacktrace: https://hastebin.com/epoxipomem.css

When i've looked into the AbstractClass it seems that the Set containing the ports isn't initialized yet even in the upper fields:
`public AbstractAllocationAction(PteroApplicationImpl impl, CompiledRoute route) {
        super(impl.getP4J(), route);
 }`
Here's my code (I get the NPE on addPorts): 
`node.getAllocationManager().createAllocation()
                        .setIP("XXXXXXXXXXXXX")
                        .addPorts("25572")
                        .execute();`

I've already checked if the node was null, it's not. I've tried to add several ports it's not working, creating a new String[] is not working either...

**Comment by mattmalec** [comment]
You should not be using the AbstractAllocationAction. Those are for internal use.

**Comment by Zentae** [comment]
I do not use it i just took a look at the class. I use Node#getAllocationManager().createAllocation();
And when setting the ports i get a NPE so i took a look at your class and your doing modification on a null Set.
