### ISSUE TITLE
Adding, Viewing and Removing Sub Users

### ISSUE THREAD

**Issue by ValentijnDevelopment** [mattmalec/Pterodactyl4J#4]
Hi,

There is no option to add, view or remove sub users.
Could this be added to this API?

According to https://dashflo.net/docs/api/pterodactyl/v1/ this feature could be implemented.

**Comment by mattmalec** [comment]
Unfortunately, the current version of this library is written for the v0.7 API. I was able to implement everything marked as working from here: https://dashflo.net/docs/api/pterodactyl/v0.7

I might start a new branch for v1.0, still thinking about what I want to do.
