### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by mrxbox98** [mattmalec/Pterodactyl4J#46]
One of my customers is having an error that seems to be caused by Pterodactyl4J.
Without any debugger the console was being flooded with nullPointerException and only the first Ptero4J action would work and all subsequent actions would not. With the debugger this was the error stream.
```
20:01:02.190 [P4J-RateLimit-Worker] DEBUG com.mattmalec.pterodactyl4j.requests.Requester - Executing request GET client/servers/0d31a0c2?include=subusers,egg
20:01:12.202 [P4J-RateLimit-Worker] DEBUG com.mattmalec.pterodactyl4j.requests.Requester - Executing request GET client/servers/0d31a0c2?include=subusers,egg
20:01:15.603 [d4j-parallel-1-1] DEBUG discord4j.gateway.DefaultGatewayClient - [G:884e7761, S:0] Sending heartbeat PT41.176026986S after last ACK
20:01:15.677 [reactor-http-epoll-3] DEBUG discord4j.gateway.DefaultGatewayClient - [G:884e7761, S:0] Heartbeat acknowledged after PT0.073351637S
20:01:22.213 [P4J-RateLimit-Worker] ERROR com.mattmalec.pterodactyl4j.requests.Requester - Requester timed out while executing a request connect timed out
20:01:22.214 [P4J-RateLimit-Worker] ERROR com.mattmalec.pterodactyl4j.requests.RateLimiter - Encountered exception trying to execute request
java.lang.NullPointerException
        at com.mattmalec.pterodactyl4j.requests.Response.getRawObject(Response.java:76)
        at com.mattmalec.pterodactyl4j.requests.Response.getObject(Response.java:98)
        at com.mattmalec.pterodactyl4j.requests.Request.setOnFailure(Request.java:81)
        at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.handleResponse(PteroActionImpl.java:149)
        at com.mattmalec.pterodactyl4j.requests.Request.handleResponse(Request.java:145)
        at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:158)
        at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:156)
        at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:70)
        at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:66)
        at com.mattmalec.pterodactyl4j.requests.RateLimiter.run(RateLimiter.java:147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:826)
20:01:22.216 [P4J-RateLimit-Worker] DEBUG com.mattmalec.pterodactyl4j.requests.Requester - Executing request GET client/servers/0d31a0c2?include=subusers,egg
20:01:29.370 [P4J-RateLimit-Worker] DEBUG com.mattmalec.pterodactyl4j.requests.Requester - Executing request GET client/servers/0d31a0c2?include=subusers,egg
20:01:29.399 [P4J-RateLimit-Worker] DEBUG com.mattmalec.pterodactyl4j.requests.Requester - Executing request GET client/servers/0d31a0c2?include=subusers,egg
20:01:29.431 [P4J-RateLimit-Worker] DEBUG com.mattmalec.pterodactyl4j.requests.Requester - Executing request GET client/servers/0d31a0c2/backups?page=1
```

I was unable to produce this on my computer and multiple of my servers. It seems to be the api request failed, but I tried calling the same api request using curl on my machines in rapid succession. My customer also tried it on their local machine as both the bot and the panel were on the same server, and all of the requests worked. I also tried running the bot on my machine with the customers panel and it was working perfectly.
I think this might be a pterodactyl error, but was unable to find any bugs on their GitHub that matched this.

**Comment by mrxbox98** [comment]
It seems to be an error with https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/requests/Request.java#L81

```java
public void setOnFailure(Response response) {
        if (response.isRateLimit()) {
            onFailure(new RateLimitedException(route, response.getRetryAfter()));
        } else
            switch (response.getCode()) {
                case 403:
                    onFailure(new LoginException("The provided token is either incorrect or does not have access to process this request."));
                    break;
                case 404:
                    onFailure(new NotFoundException("The requested entity was not found."));
                    break;
                case 422:
                    onFailure(new MissingActionException("The request is missing required fields.", response.getObject()));
                    break;
                case 500:
                    onFailure(new ServerException("The server has encountered an Internal Server Error."));
                    break;
                default:
                    onFailure(new HttpException(String.format("Pterodactyl4J has encountered a %d error.", response.getCode()), response.getObject()));
                    break;
            }
    }
```

The error code is none of those so it goes to the default and then when it calls the getObject in the response it causes an error meaning it will not be able to call onFailure.

**Comment by fo0** [comment]
Im getting the error too and all I can currently say is that it happens after hours, maybe 10 or 12 hours (my pterodactyl .env rate limit is pretty high, so I think thats not the problem)

My usage of the client is s.th. like
1. create the PteroApplication (not create again)
2. create the PteroClient (not create again)

using it around 10 hours and then massiv log spam of, ending up in app crash
```java
log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : <my panel domain>
log | java.lang.NullPointerException
log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.RateLimiter   : Encountered exception trying to execute request
log | java.lang.NullPointerException
log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : <my panel domain>
log | java.lang.NullPointerException
log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.RateLimiter   : Encountered exception trying to execute request
log | java.lang.NullPointerException
log | java.lang.NullPointerException
log | java.lang.NullPointerException
log | java.lang.NullPointerException
```

**Comment by mrxbox98** [comment]
> Im getting the error too and all I can currently say is that it happens after hours, maybe 10 or 12 hours (my pterodactyl .env rate limit is pretty high, so I think thats not the problem)
> 
> My usage of the client is s.th. like
> 
> 1. create the PteroApplication (not create again)
> 2. create the PteroClient (not create again)
> 
> using it around 10 hours and then massiv log spam of, ending up in app crash
> 
> ```java
> log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : <my panel domain>
> log | java.lang.NullPointerException
> log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.RateLimiter   : Encountered exception trying to execute request
> log | java.lang.NullPointerException
> log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : <my panel domain>
> log | java.lang.NullPointerException
> log | ERROR 1 --- [ateLimit-Worker] c.m.pterodactyl4j.requests.RateLimiter   : Encountered exception trying to execute request
> log | java.lang.NullPointerException
> log | java.lang.NullPointerException
> log | java.lang.NullPointerException
> log | java.lang.NullPointerException
> ```

How did you set rate limiting in the pterodactyl env?

**Comment by mattmalec** [comment]
P4J handles rate limits just fine, this sounds more like an issue with several failed requests, and P4J is attempting to read a ResponseBody that doesn't actually exist.

**Comment by fo0** [comment]
Just FYI @mrxbox98 I took it from the code, difficult to find in any doc ...
for your .env in ptero root folder -> [Pterodactyl Panel Code](https://github.com/pterodactyl/panel/blob/develop/config/http.php)

**Comment by fo0** [comment]
**As an update here:**
After a short while (days) the error disappeared for me with no reason and since that it not appeared again for me.

**Comment by mattmalec** [comment]
I expect this to have been an awkward edge case scenario with your environment. If this issues persists, please reopen this issue and I'll dig into it further.
