### ISSUE TITLE
ApplicationServer.retrieveAllocation() returning null

### ISSUE THREAD

**Issue by LooFifteen** [mattmalec/Pterodactyl4J#5]
Hey, I've looked through the code and I think I noticed that you were getting "allocation" from attributes, however I believe it's outside of attributes. I don't know if this makes any sense but here's an example of server data from https://dashflo.net/docs/api/pterodactyl/v0.7/#get-server-information:
```json
{
  "object": "server",
  "attributes": {
    "id": 2,
    "external_id": null,
    "uuid": "47a7052b-f07e-4845-989d-e876e30960f4",
    "identifier": "47a7052b",
    "name": "Survival",
    "description": "gsk;ljgkj;hgdakl;gha",
    "suspended": false,
    "limits": {
      "memory": 2048,
      "swap": -1,
      "disk": 10000,
      "io": 500,
      "cpu": 300
    },
    "feature_limits": {
      "databases": 10,
      "allocations": 0
    },
    "user": 1,
    "node": 2,
    "allocation": 3,
    "nest": 1,
    "egg": 4,
    "pack": null,
    "container": {
      "startup_command": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
      "image": "quay.io/pterodactyl/core:java",
      "installed": true,
      "environment": {
        "SERVER_JARFILE": "server.jar",
        "VANILLA_VERSION": "latest",
        "STARTUP": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
        "P_SERVER_LOCATION": "test",
        "P_SERVER_UUID": "47a7052b-f07e-4845-989d-e876e30960f4"
      }
    },
    "updated_at": "2018-11-20T02:52:37+00:00",
    "created_at": "2018-09-29T22:50:16+00:00"
  }
}
```

**Comment by fayeinmay** [comment]
@SuperLegoLuis No, the allocation field is within the attributes object. I think your eyes are misleading you there. You can put that json into a tool like https://jsoneditoronline.org and will see that the allocation field is within that attribute object.

**Comment by LooFifteen** [comment]
Sorry about that, I was just thinking that was the cause to the issue I have. The `Allocation` from a server is returning `null` from every method. Any reason why it would do this?

**Comment by fayeinmay** [comment]
Not developed on this actually, so @mattmalec would need to help you on that. (I'd recommend opening a new more fitting issue though.)

**Comment by mattmalec** [comment]
@SuperLegoLuis Please open a new issue and I’ll be happy to look into this.
