### ISSUE TITLE
retrieveEggs and nests maybe buggy

### ISSUE THREAD

**Issue by fo0** [mattmalec/Pterodactyl4J#54]
playing around with some versions later then `2.BETA_102`

my use case is fetching all eggs and all nests

code always same:
```java
    final PteroApplication client = PteroBuilder.createApplication(
        "https://my-pterodactyl-panel",
        "token");

    log.info("eggs: {}", client.retrieveEggs()
                               .execute()
                               .size());

    log.info("nests: {}", client.retrieveNests()
                                .execute()
                                .size());
```

2.BETA_102
- everything fine, sometimes rate limiter, but not that often
- webhooks / server-logs not work

logs:
```java
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?page=1&include=servers,eggs
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?page=2&include=servers,eggs
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests/1/eggs?include=variables,nest,servers
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests/2/eggs?include=variables,nest,servers
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests/<<<<3,4.5....94....>>>>
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests/95/eggs?include=variables,nest,servers
           main] c.e.p4jexample1.P4jExample1Application   : eggs: 157
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?page=1&include=servers,eggs
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?page=2&include=servers,eggs
           main] c.e.p4jexample1.P4jExample1Application   : nests: 90
```

RESULT:
```java
           main] c.e.p4jexample1.P4jExample1Application   : eggs: 157
           main] c.e.p4jexample1.P4jExample1Application   : nests: 90
```

2.BETA_117
... to latest
2.BETA_132
- egg and nest apis partially broken
- webhooks / server-logs works fine!

```java
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=1
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 15
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=2
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 30
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=3
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 45
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=4
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 60
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=5
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 75
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=6
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 90
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=7
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 0 entities, cache size: 90
          main] c.e.p4jexample1.P4jExample1Application   : eggs: 0
[ateLimit-Worker] c.m.pterodactyl4j.requests.Requester     : Executing request GET application/nests?include=servers,eggs&per_page=0&page=1
[ateLimit-Worker] c.m.p.requests.PaginationAction          : Cache enabled: caching 15 entities, cache size: 15
          main] c.e.p4jexample1.P4jExample1Application   : nests: 15
```

RESULT:
```java
          main] c.e.p4jexample1.P4jExample1Application   : eggs: 0
          main] c.e.p4jexample1.P4jExample1Application   : nests: 15
```

# Question
any idea whats up with the egg / nest part? its same example-code and i expected that the results should be equal

Thanks in advance

**Comment by mattmalec** [comment]
How are you running the code with the newer P4J version? There has been changes to the PteroAction implementation of paginated entities since 102 and the code you've shown above would only return the first page.

You can use `PaginationAction#all` in your testing use case, which returns a PteroAction like normal and you wouldn't have to change much. However, I would recommend using the async for-each and take functions.

**Comment by fo0** [comment]
> How are you running the code with the newer P4J version? There has been changes to the PteroAction implementation of
> paginated entities since 102 and the code you've shown above would only return the first page.

yeah I can switch the versions between 102 and 132 without chaning the code shown above. Isn't that right?

> You can use PaginationAction#all in your testing use case, which returns a PteroAction like normal and you wouldn't have to
> change much. However, I would recommend using the async for-each and take functions.

I changed the code for nests to 
```java
    log.info("nests: {}", client.retrieveNests()
                                .all()
                                .execute()
                                .size());
```
and works, thanks! (maybe: shouldn't the default behavior of `retrieveNests().execute()` not the implicit `#all` ?)

for `retrieveEggs` it doesn't work, could not find any paginated methods, maybe a hint?
```java
    log.info("eggs: {}", client.retrieveEggs()
                               .execute()
                               .size());
```

**Comment by mattmalec** [comment]
The intention of changing the default behavior is just how the PaginationAction works. Every time a request is made, it updates the next page and calls #execute internally. If we use the new for-each or take actions, it's the more preferred way to loop over servers. 

If you wanted to do something that required looping over servers only until the 3rd page, you can stop the loop midway without needing to retrieve every single available page.

I can look into the retrieveEggs thing, but glad to hear nests are working as expected.

**Comment by fo0** [comment]
> The intention of changing the default behavior is just how the PaginationAction works. Every time a request is made, it updates the next page and calls #execute internally. If we use the new for-each or take actions, it's the more preferred way to loop over servers.

alright, i understand. The most implementations are using something like Pageable/Page like explained [here](https://www.baeldung.com/spring-data-jpa-pagination-sorting) but anyway, after getting your hint, everything is fine :) - thank you

> If you wanted to do something that required looping over servers only until the 3rd page, you can stop the loop midway without needing to retrieve every single available page.

Thats a good thing about pageable stuff, thats true. But I think mostly you will using the `fetchById` apis directly.


> I can look into the retrieveEggs thing, but glad to hear nests are working as expected.

Thank you! 👍

**Comment by Zentae** [comment]
Bump !

**Comment by mattmalec** [comment]
This has been fixed in `2.BETA_133`
