### ISSUE TITLE
Server deletion API

### ISSUE THREAD

**Issue by OpenSource03** [mattmalec/Pterodactyl4J#61]
Hi there!

I was not able to find a way to delete a server using this wrapper. Is there a way? And if not, why?

Regards

**Comment by OpenSource03** [comment]
Found a solution, however, I'd still suggest making a better documentation :)

**Comment by mattmalec** [comment]
I agree that documentation is certainly lacking, but this searchable over on the P4J docs: https://ci.mattmalec.com/job/Pterodactyl4J/javadoc

If you search for `delete`, tons of options come up. I tried to make the code as human-readable as possible so even without detailed documentation, it should still hopefully be somewhat comprehensible.

Feel free to join the Discord if you get stuck, I'm usually available there.
