### ISSUE TITLE
Gradle not adding dependency to classpath

### ISSUE THREAD

**Issue by orbyfied** [mattmalec/Pterodactyl4J#65]
I have a `build.gradle` with the following code:
[build.gradle](https://pastes.dev/lmKy9Rjzou)
When I reload, I can see in IntelliJ it downloading the pom.xml but no jars, additionally when I open the `compileClasspath` or `runtimeClasspath` tabs under the Gradle action window on the right, nothing is there and in the code it doesn't provide any of the classes.

**Comment by orbyfied** [comment]
I've downloaded the JAR file and I am now using it as dependency, would be nice if it worked through a normal dependency though.

**Comment by mattmalec** [comment]
Your implementation should be `implementation 'com.mattmalec:Pterodactyl4J:2.BETA_139'`. Make sure you're not prefixing the `v` to it. I should document that more clearly.
