### ISSUE TITLE
What cause this problem and how to solve it?

### ISSUE THREAD

**Issue by steven11304** [mattmalec/Pterodactyl4J#69]
08:11:55 [SEVERE] com.mattmalec.pterodactyl4j.exceptions.ServerException: The server has encountered an Internal Server Error.

08:11:55 [SEVERE]     at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.execute(PteroActionImpl.java:99)

08:11:55 [SEVERE]     at com.mattmalec.pterodactyl4j.PteroAction.execute(PteroAction.java:97)

08:11:55 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerStarter.lambda$runPanelAction$2(:121)

08:11:55 [SEVERE]     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)

08:11:55 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Goksi** [comment]
You should check your pterodactyl logs, it's throwing http 500

**Comment by steven11304** [comment]
Hi , I found these errors in the  pterodactyl  logs
ERROR: [May 29 23:56:36.161] error while handling HTTP request error=websocket: request origin not allowed by Upgrader.CheckOrigin request_id=4f0a31f3-bd6c-4a5c-b1ba-a80d0bfd6a80 server_id=2a4a3c41-dec6-47f7-a630-96f5710bc910 status=403 url=/api/servers/2a4a3c41-dec6-47f7-a630-96f5710bc910/ws

Stacktrace:
websocket: request origin not allowed by Upgrader.CheckOrigin
github.com/pterodactyl/wings/router.getServerWebsocket
	github.com/pterodactyl/wings/router/router_server_ws.go:37
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/pterodactyl/wings/router/middleware.ServerExists.func1
	github.com/pterodactyl/wings/router/middleware/middleware.go:158
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.8.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/pterodactyl/wings/router/middleware.AttachApiClient.func1
	github.com/pterodactyl/wings/router/middleware/middleware.go:51
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/pterodactyl/wings/router/middleware.AttachServerManager.func1
	github.com/pterodactyl/wings/router/middleware/middleware.go:42
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/pterodactyl/wings/router/middleware.SetAccessControlHeaders.func1
	github.com/pterodactyl/wings/router/middleware/middleware.go:135
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/pterodactyl/wings/router/middleware.CaptureErrors.func1
	github.com/pterodactyl/wings/router/middleware/middleware.go:68
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/pterodactyl/wings/router/middleware.AttachRequestID.func1
	github.com/pterodactyl/wings/router/middleware/middleware.go:33
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.8.1/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.8.1/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.8.1/gin.go:572
net/http.serverHandler.ServeHTTP
	net/http/server.go:2916
net/http.(*conn).serve
	net/http/server.go:1966
runtime.goexit
	runtime/asm_amd64.s:1571

**Comment by steven11304** [comment]
Here is the full error log
https://paste.gg/p/anonymous/35a8459fc24240b095ba11ad45af01ef

**Comment by Goksi** [comment]
You should refer to [pterodactyl discord](https://discord.gg/pterodactyl) in future, but regarding this problem your URL in wings config.yml doesn't match your actual panel url, or if its for ws, just add your domain into `allowed_origins` in config.yml
