### ISSUE TITLE
Unable to import maven dependency

### ISSUE THREAD

**Issue by JacobPassam** [mattmalec/Pterodactyl4J#7]
**Error:** `Could not transfer artifact com.mattmalec.Pterodactyl4J:Pterodactyl4J:pom:1.1 from/to jcenter (http://jcenter.bintray.com): Authorization failed for http://jcenter.bintray.com/com/mattmalec/Pterodactyl4J/Pterodactyl4J/1.1/Pterodactyl4J-1.1.pom 403 Forbidden
`

**Code:** https://pastie.io/apvwxj.xml

**Comment by mattmalec** [comment]
This has nothing to do with Pterodactyl4J, but, you need to use HTTPS with Bintray.

**Comment by JacobPassam** [comment]
Sorry, found the issue: jcenter is only available over https.

**Comment by JacobPassam** [comment]
oh it seems we commented at the same time. apologies.
