### ISSUE TITLE
Api support for mounts

### ISSUE THREAD

**Issue by PedroMPagani** [mattmalec/Pterodactyl4J#70]
is there any API to mount specific mount to servers?

**Comment by mattmalec** [comment]
There's no user-facing API in Pterodactyl that supports mounts unfortunately. https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php

**Comment by PedroMPagani** [comment]
> There's no user-facing API in Pterodactyl that supports mounts unfortunately. https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php

Makes sense, do you know any possible way that I could automatically give this to all containers?
Maybe with a query on DB depending on how ptero is storing these infos?
