### ISSUE TITLE
How to get the client id when create?

### ISSUE THREAD

**Issue by Clayun** [mattmalec/Pterodactyl4J#72]
and how to get the client id?

_Originally posted by @Clayun in https://github.com/mattmalec/Pterodactyl4J/issues/1#issuecomment-1696316187_

**Comment by Clayun** [comment]
`PteroAction<ApplicationServer> action = api.createServer()
                .setName(creator.getName())
                .setDescription(creator.getDescription())
                .setOwner(api.retrieveUserById(creator.getOwnerId()).execute())
                .setEgg(egg)
                .setLocation(location)
                .setAllocations(creator.getAllocations())
                .setDatabases(creator.getDatabases())
                .setCPU(creator.getCPU())
                .setDisk(creator.getDisk(), DataType.GB)
                .setMemory(creator.getMemory(), DataType.GB)
                .setSwap(creator.getSwap(), DataType.MB)
                .setDockerImage(creator.getDockerImage())
                .setPort(creator.getPort())
                .startOnCompletion(creator.isStartOnCompletion())
                .setEnvironment(map);

        ApplicationServer server = action.execute();

        return server.getId();`

in my code , this server.getId() is application server id,when i use this id in client api,it show me the "The requested entity was not found"

**Comment by mattmalec** [comment]
did you figure this out?
